apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-web
  template:
    metadata:
      labels:
        app: patient-web
    spec:
      containers:
      - name: patient-web
        image: bagato220/PatientInterface  # Will be overridden by CI/CD
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"