name: Deploy Patient Web  Application 
run-name: Deploy Patient Web by ${{ github.actor }} and Event is ${{ github.event_name }}

on: 
  push:
    branches:
      - main
    
jobs:
  CI-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' 

      - name: Install Requirements
        working-directory: ./project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test Linting 
        working-directory: ./project
        run: |
          pip install flake8
          flake8 .
        continue-on-error: true

      - name: Testing 
        working-directory: ./project
        run: | 
          pip install pytest
          pytest 
        continue-on-error: true

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Docker 
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./project/
          push: true
          tags: ziadhamdymohammed/PatientInterface:${{ github.run_number }}